# Generated by Django 5.1.6 on 2025-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
